# Parent configuration with shared settings
name = "creatorino-api"
type = "javascript"
account_id = "" # Add your Cloudflare account ID here
compatibility_date = "2023-09-01"

# This file serves as a template and documentation
# Each worker should have its own wrangler.toml in its subdirectory
# The .dev.vars file is shared across all workers

# Environment variables shared by all workers
[vars]
SUPABASE_URL = ""
SUPABASE_KEY = ""
