# Parent configuration with shared settings
name = "creatorino-api"
main = "index.js"
compatibility_date = "2023-09-01"
account_id = "5267338e6e637da4f95322d02fba6025" 
workers_dev = true

# Remove the route line since we're using workers_dev = true
# This will make the worker available at creatorino-api.benjamin-f-mcdaniel.workers.dev

# Environment variables
[vars]
SUPABASE_URL = ""
SUPABASE_KEY = ""

# Module format for importing
[build]
command = ""
[build.upload]
format = "modules"
main = "./index.js"

