# Parent configuration with shared settings
name = "creatorino-api"
main = "index.js"
compatibility_date = "2023-09-01"
account_id = "" # Add your Cloudflare account ID here
workers_dev = true
route = "api.benjamin-f-mcdaniel.workers.dev/*"

# Environment variables
[vars]
SUPABASE_URL = ""
SUPABASE_KEY = ""

# Module format for importing
[build]
command = ""
[build.upload]
format = "modules"
main = "./index.js"
